services:
  api1:
    build:
      context: .
      dockerfile: Dockerfile.api1
    ports:
      - "8080:5000"
    environment:
      - API2_URL=http://api2:5001
    depends_on:
      - api2
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  api2:
    build:
      context: .
      dockerfile: Dockerfile.api2
    ports:
      - "8081:5001"
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

networks:
  microservices-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  api_logs:
    driver: local